kind: Service
metadata:
  name: indexing-service
  labels:
    app: indexing-service
    name: indexing-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: indexing-service
    name: indexing-service
